import numpy as np
from msc.generation.crop import crop
import json
import matplotlib.pyplot as plt
from skimage import io


# the script collects data generated by generate_xml_and_pc.py in the four directory data1, data2, data3, data4
# into the single directory quarter_measure_length


other_data = dict()
lexicon = ['6', '<START>', '12', '7', 'rest', 'pitch', '3', 'E', '}', 'quarter', '2', '16', '4', 'C', 'measure', '<END>', '0', 'staff', 'duration', 'G', 'chord', 'D', '5', 'F', 'B', 'note', 'backup', 'type', 'A', '-1', '1', '<PAD>']
word_to_ix = {word: ix for ix, word in enumerate(lexicon)}
ix_to_word = {ix: word for ix, word in enumerate(lexicon)}
other_data['lexicon'] = {'word_to_ix': word_to_ix, 'ix_to_word': ix_to_word}
other_data['aux_data'] = []


for i in range(1, 5):
    with open(f'data/data{i}/extra_data{i}.json') as f:
        extra_data = json.load(f)
    for j in range(2):
        png_path = f'data/data{i}/{j}-1.png'
        svg_path = f'data/data{i}/{j}-1.svg'
        image_np = crop(png_path, svg_path)
        image_np = (255*image_np).astype(np.uint8)
        io.imsave(f'data/quarter_measure_data/{10000*(i-1)+j}.png', image_np)
        measure_length = extra_data[j]['measure_length']
        key_number = extra_data[j]['key_number']
        pc = extra_data[j]['pc']
        d = {'measure_length': measure_length, 'key_number': key_number, 'pc': [word_to_ix[x] for x in pc]}
        other_data['aux_data'].append(d)

with open('data/quarter_measure_data/other_data.json', 'w+') as f:
    json.dump(other_data, f)