# Generated by Django 2.2.4 on 2019-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190919_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='time_signature',
            field=models.CharField(max_length=64),
        ),
    ]
