# Generated by Django 2.2.4 on 2019-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190920_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.FileField(upload_to='', verbose_name='Page')),
                ('key', models.CharField(max_length=64)),
                ('time_signature', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='UploadedMeasure',
        ),
    ]
